apiVersion: v1
kind: ServiceAccount
metadata:
  name: credit-scoring-api
  namespace: credit-scoring
  annotations:
    iam.gke.io/gcp-service-account: credit-scoring-api@your-project.iam.gserviceaccount.com