apiVersion: v1
kind: Namespace
metadata:
  name: credit-scoring
  labels:
    name: credit-scoring
    part-of: credit-scoring-system
    managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    name: mlflow
    component: ml-experiments
    managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    component: observability
    managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    component: observability
    managed-by: kustomize